# -*- coding: utf-8 -*-
"""rock_paper_scissors.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1e-fJy2DcmMPsrn0Tj7KsjCzvDfDSCm
"""

import random

def get_user_choice():
    while True:
        user_choice = input("Enter your choice (rock, paper, or scissors): ").lower()
        if user_choice in ['rock', 'paper', 'scissors']:
            return user_choice
        else:
            print("Invalid choice. Please enter 'rock', 'paper', or 'scissors'.")

def play_game():
    choices = ['rock', 'paper', 'scissors']
    computer_choice = random.choice(choices)
    user_choice = get_user_choice()

    print(f"You chose: {user_choice}")
    print(f"Computer chose: {computer_choice}")

    if user_choice == computer_choice:
        print("It's a tie!")
    elif (user_choice == 'rock' and computer_choice == 'scissors') or \
         (user_choice == 'paper' and computer_choice == 'rock') or \
         (user_choice == 'scissors' and computer_choice == 'paper'):
        print("Congratulations! You win!")
    else:
        print("Sorry! Computer wins!")

if __name__ == "__main__":
    print("Welcome to the Rock Paper Scissors game!")
    play_game()